# Generated by Django 2.2.17 on 2020-12-30 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
