# Generated by Django 2.2.17 on 2021-01-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20210126_2237'),
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-commit_date']},
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repository_id',
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.Repository'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
