# Generated by Django 2.2.17 on 2020-12-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
