# Generated by Django 2.2.17 on 2021-01-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_auto_20201230_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='user_id',
        ),
    ]
