# Generated by Django 2.2.17 on 2020-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
